config/routes.rb
 Rails.application.routes.draw do

resources :events do
  resources :reservations
end
resources :users
resources :sessions

  get '/about', to: 'home#about', :as => "about"
  get '/terms', to: 'home#terms', :as => "terms"
  get '/contact', to: 'home#contact', :as => "contact"
  get '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'
  get '/register', to: 'users#new'
  get '/home', to: redirect('/')
  root :to => 'home#home'

  get '/blog', to: 'home#blog', :as => "blog"

  

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :events
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :category
  belongs_to :user
  has_many :reservations
    has_many :users, through: :reservations

validates :category_id, presence: true
validates :title, presence: true
validates :description, presence: true
validates :date, presence: true
validates :time, presence: true
validates :location, presence: true
end

app/models/frequency.rb
class Frequency < ActiveRecord::Base
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :user
  belongs_to :event

end

app/models/rsvp_cap.rb
class RsvpCap < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
has_secure_password

has_many :events
has_many :reservations

 has_attached_file :avatar, 
 :styles => { :medium => "300x300>", :thumb => "90x90>" }, 
 :default_url => ":style/missing.png",
 :storage => :s3,
 :bucket => 'konverge'
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

validates :name, presence: true
validates :email, presence: true
validates :password, presence: true
validates :terms_of_service, acceptance: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

protect_from_forgery with: :exception

helper_method :current_user
before_action :require_user

def current_user
  User.find_by(id: session["user_id"])  
end

def require_user
if current_user.nil?
    redirect_to login_path
end
end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
skip_before_action :require_user, only: [:index,]
before_filter :current_user
before_action :find_event
before_action :event_params, only: [:create, :update]
helper_method :sort_column, :sort_direction
  
def index
@event = Event.where("date > ?", Time.zone.now.beginning_of_day)
@events = @event.order(sort_column + " " + sort_direction)

@pastevent = Event.where("date < ?", Time.zone.now.beginning_of_day)
@pastevents = @pastevent.sort_by {|h| h[:date]}
end

def show
# do something with params
@reservations = @event.reservations
@reservation = Reservation.new
@eventend = @event.time + (60*60*2)
end

def new
@event = Event.new
end

def create
  @event = Event.create(event_params)
  @event.user_id = current_user.id
  @event.save
    if @event.valid?
      redirect_to events_path, notice: "Event created successfully"
    else 
      render "new", alert: "Please recheck the errors below"
      Event.name
    end
end

def edit
# do something with params
end

def update
    if @event.update_attributes(event_params)
      redirect_to event_path, notice: "Event updated"
    else 
      render "new", alert: "Please recheck the errors below"
      Event.name
    end
end

def destroy
    @event.destroy
    redirect_to events_path, notice: "Event deleted"
end

def find_event
  @event = Event.find_by(id: params["id"])
end

def event_params
  event_params = params.require(:event).permit(:category_id, :title, :description, :date, :time, :location)
end

private

def sort_column
  Event.column_names.include?(params[:sort]) ? params[:sort] : "Date"
end

def sort_direction
  %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
skip_before_action :require_user
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
skip_before_action :require_user
before_action :find_event

def index
end

def show
end

def new
@reservation = Reservation.new
end

def create
reserv_params = params.require(:reservation).permit(:comment)
  @reservation = @event.reservations.new(reserv_params)
  @reservation.user_id = current_user.id
    if @reservation.save
      redirect_to @event, notice: "Your spot has been reserved"
    else 
      redirect_to @event, alert: "Something went wrong"
    end
end



def edit
end

def update
end

def destroy
end

def find_event
    @event = Event.find_by(id: params["event_id"])
end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

skip_before_action :require_user

  def create
    # params["email"] => the email address
    # params["password"] => the password
    # Do authentication
    # Redirect to the root_path
    # Display a notice that login was either successful or unsuccessful

    user = User.find_by(email: params["email"])
    if user && user.authenticate(params["password"])
      session["user_id"] = user.id
      redirect_to events_path, notice: "Login successful"
    else
      redirect_to login_path, alert: "Login unsuccessful"
    end

  end

  def destroy
    # Do sign-out
    session["user_id"] = nil
    redirect_to root_path, notice: "See ya later!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
skip_before_action :require_user, only: [:new, :create, :show]
before_action :find_user
skip_before_action :user_params, except: [:create, :update]

def index
redirect_to root_path, notice: "Only administrators can see that page"
# @users = User.all 
end

def show
# do something with params
@reservations = Reservation.where(user_id: @user)
end

def new
@user = User.new
end

def create
  @user = User.create(user_params)
    if @user.valid?
      redirect_to root_path, notice: "You're account was created successfully"
    else 
      render "new"
      User.name
    end
end


def edit
end

def update
    if @user.update_attributes(user_params)
      redirect_to user_path, notice: "You're account was updated successfully"
    else 
      render "new", alert: "Please recheck the errors below"
      User.name
    end
end

def destroy
    @user.destroy
    redirect_to root_path
end

def find_user
 @user = User.find_by(id: params["id"])
end

def user_params
user_params = params.require(:user).permit!
end


end

app/helpers/application_helper.rb
module ApplicationHelper
	def site_name
    # Change the value below between the quotes to be the websites name.
    "Konverge @ Kellogg"
  end

  def site_url
    if Rails.env.production?
      # Place your production URL in the quotes below
      root_path
    else
      # Our dev & test URL
      "http://localhost:3000"
    end
  end

  def meta_author
    # Change the value below between the quotes.
    "Joshua Borin"
  end

  def meta_description
    # Change the value below between the quotes.
    "Website for students to meetup"
  end

  def meta_keywords
    # Change the value below between the quotes.
    "Add your keywords here"
  end

  # Returns the full title on a per-page basis.
  # No need to change any of this we set page_title and site_name elsewhere.
  def full_title(page_title)
    if page_title.empty?
      site_name
    else
      "#{page_title} | #{site_name}"
    end
  end

def sortable(column, title=nil)
  title ||= column.titleize
  direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
  link_to title, :sort => column, :direction => direction
end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/events/_form.html.erb
<%= simple_form_for(@event, html: { class: 'form-horizontal' }) do |form|%>
                        <%= render 'shared/error_messages', object: @event %>
                                
                            <div class="form-group">
                                <%= form.label :category_id, class: "col-lg-2 control-label" %>

                                    <div class="col-lg-3">
                                        <%= form.input_field :category_id, as: :select, collection: Category.all, class: "form-control"%> 
                                    </div>
                                </div>


                                <div class="form-group">
                                <%= form.label :title, class: "col-lg-2 control-label" %>

                                    <div class="col-lg-6">
                                        <%= form.text_field :title, class: "form-control", placeholder: "Short distinct name"%> 
                                    </div>
                                </div>

                                <div class="form-group">
                                    <%= form.label :description, class: "col-lg-2 control-label" %>

                                    <div class="col-lg-6">
                                        <%= form.text_area :description, class: "form-control", placeholder: "A more detailed description of your event"%> 
                                   
                                    </div>
                                </div>

                                <div class="form-group">
                                     <%= form.label :date, class: "col-lg-2 control-label" %>

                                    <div class="col-lg-3">
                                        <%= form.date_field :date, class: "form-control" %> 
                                    </div>
                                </div>
 
                                <div class="form-group">
                                    <%= form.label :time, class: "col-lg-2 control-label" %>

                                    <div class="col-lg-3">
                                       <%= form.time_field :time, class: "form-control" %> 

                                    </div>
                                </div>

                                <div class="form-group">
                                    <%= form.label :location, class: "col-lg-2 control-label" %>

                                    <div class="col-lg-6">
<%= form.text_field :location, class: "form-control", placeholder: "Enter location and exact spot to meet" %> 
                                    </div>
                                </div>                                
                         
                                <div class="col-lg-10 col-lg-offset-2">
<%= form.button :submit, class: "btn btn-success" %>  &nbsp; <%= link_to "Cancel", events_path, class: "btn btn-warning"  %>  
                                </div>
                                    <% end %> 

app/views/events/_table.html.erb
<table class="table table-striped table-hover ">
  <thead>
    <tr>
      <th></th>
      <th>Category</th>
      <th>Title</th>
      <th>Description</th>
      <th><%= sortable "Date" %></th>
      <th><%= sortable "Time" %></th>
      <th>Location</th>
       <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% object.each do |event| %>

    <tr>
      <td><i class="<%= event.category.logo %>"></i></td>
      <td><%= event.category.name %></td>
      <td><%= link_to event.title, event_path(event.id) %></td>
      <td><%= event.description %></td>
      <td><%= event.date.strftime("%D") %></td>
      <td><%= event.time.strftime("%l:%M %p") %></td>
      <td><%= event.location %></td>
      <td><%= link_to "Edit", edit_event_path(event) %></td>
      <td><%= link_to "Delete", event_path(event), method: :delete, data: {confirm:'Are you really sure? BE CAREFUL'} %> </td>
    </tr>
<% end %>
  </tbody>
</table> 

app/views/events/edit.html.erb
<% provide(:title, 'Edit Event') %>
<!DOCTYPE html>
<html>
<head>
    <title></title>
</head>

<body>
    <div class="container">
        <!-- Example row of columns -->

        <div class="row">
            <div class="col-md-9 col-md-offset-1">
            <br>
                         <legend><h1> Edit the event</h1></legend>
                       <%= render "form", title: 'Update Event' %>
                                                
               
            </div>
        </div>

        
    </div>
</body>
</html>

app/views/events/index.html.erb
<% provide(:title, 'Events') %>

<h1> Showing <%= @events.count %> live events </h1>

<%= render 'table', object: @events %>  

<div class="btn-group">
    <%= link_to "Create an event", new_event_path, class: "btn btn-default btn-lg btn-primary" %>
</div> 

<h1> Showing <%= @pastevents.count %> past events </h1>

<%= render 'table', object: @pastevents %>   

app/views/events/new.html.erb
<% provide(:title, 'New Event') %>
<!DOCTYPE html>
<html>
<head>
    <title></title>
</head>

<body>
    <div class="container">
        <!-- Example row of columns -->

        <div class="row">
            <div class="col-md-9 col-md-offset-1">
            <br>
                        <legend><h1> Create an event</h1></legend>
                       <%= render "form", title: 'Create Event' %>

                          
               
            </div>
        </div>

        
    </div>
</body>
</html>

app/views/events/show.html.erb
<% provide(:title, 'Event') %>
<hr class="">
    <div class="container target">
        <div class="row">
            <div class="col-sm-8">
                <h1 class=""><%= @event.title %>
                </h1>
                <p class="lead">
                    <b>Description:</b><%= @event.description %>
                </p>
                <br>
                </div>
                <div class="col-sm-4"></div>
            </div>
            <div class="row">
                <div class="col-sm-4">
                    <!--left col-->
                    <ul class="list-group">
                        <li class="list-group-item text-right">
                            <span class="pull-left">
                                <strong>Organizer:</strong>
                            </span><%= @event.user.name %>
                        </li>
                        <li class="list-group-item text-right">
                            <span class="pull-left">
                                <strong>Category:</strong>
                            </span><%= @event.category.name %>
                        </li>
                        <li class="list-group-item text-right">
                            <span class="pull-left">
                                <strong>Date:</strong>
                            </span><%= @event.date.strftime("%B %e, %Y (%a)") %>
                        </li>
                        <li class="list-group-item text-right">
                            <span class="pull-left">
                                <strong>Time:</strong>
                            </span><%= @event.time.strftime("%l:%M %p") %>
                        </li>
                        <li class="list-group-item text-right">
                            <span class="pull-left">
                                <strong>Location:</strong>
                            </span><%= @event.location %>
                        </li>
                    </ul>
                    <a data-target="#basicModal" class="btn btn-primary btn-lg btn-block" data-toggle="modal" >
                        <i class="fa fa-ticket fa-2x"></i>
                        <br>
                            <br>Join this Event
                            </a>
                            <div class="modal fade" id="basicModal">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                    <%= simple_form_for([@event, @reservation]) do |form|%>
                                        <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                                            <h4 class="modal-title">Reserve your spot for "<%= @event.title %>"
                                            </h4>
                                        </div>
                                        <div class="modal-body">
                                            <div class="form-group">
                                                <span class="strong"><%= form.label "Leave a comment about the event?",  required: false %>
                                                </span>
                                                <div class="col-lg-8"><%= form.input :comment, input_html: {class: "form-control"}, label: false %>
                                                </div>
                                            </div>
                                        </div>
                                        <br>
                                            <div class="modal-footer"><%= form.button :submit, class: "btn btn-success" %>
                                                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                                            </div>
                                        </div><% end %>
                                    </div>
                                </div>
                                <br>
                                    <a href="http://infinite-falls-5300.herokuapp.com/events/<%= @event.id %>" title="Add to Calendar" class="addthisevent">
    Add to Calendar 
    
                                        <span class="_start"><%= @event.date.strftime("%m/%d/%Y ") %><%= @event.time.strftime("%k:%M:%S %p") %>
                                        </span>
                                        <span class="_end"><%= @event.date.strftime("%m/%d/%Y ") %><%= @eventend.strftime("%k:%M:%S %p") %>
                                        </span>
                                        <span class="_zonecode">11</span>
                                        <span class="_summary"><%= @event.title %>
                                        </span>
                                        <span class="_description"><%= @event.description %>
                                        </span>
                                        <span class="_location"><%= @event.location %>
                                        </span>
                                        <span class="_organizer"><%= @event.user.name %>
                                        </span>
                                        <span class="_organizer_email"><%= @event.user.email %>
                                        </span>
                                        <span class="_all_day_event">false</span>
                                        <span class="_date_format">MM/DD/YYYY</span>
                                    </a>
                                </div>
                                <!--/col-3-->
                                <div class="col-sm-8" contenteditable="false" style="">
                                    <div class="panel panel-default">
                                        <div class="panel-heading">Other people attending</div>
                                        <div class="panel-body"><% @reservations.each do |show| %>
                                            <div class="col-sm-4 text-center"><%= image_tag show.user.avatar.url(:thumb) %>
                                                <p>
                                                    <strong><%= link_to show.user.name, user_path(show.user.id) %>
                                                    </strong>
                                                    <br>
                                                        <em><%= show.comment %>
                                                        </em>
                                                    </p>
                                                    <br>
                                                    </div><% end %>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div> 

 

app/views/home/blog.html.erb
<% provide(:title, 'Blog') %>
<!DOCTYPE html>
<html>
<body>

<h1>Blog</h1>

<p>Blog goes here <p>


<p>Thanks for visiting!</p>

</body>
</html>

app/views/home/contact.html.erb
<% provide(:title, 'Contact') %>
<h1> Contact</h1>

 
<p>If you have any questions or comments, please reach out:
</br><a href="mailto:josh@joshborin.com?Subject=Hey%20there%20Josh" target="_top">Josh@joshborin.com</a>
</br><a href="https://twitter.com/joshborin">@joshborin</a> on Twitter</p>

app/views/home/terms.html.erb
<% provide(:title, 'Terms') %>
<h1> Terms and Conditions</h1>
<p> Here are our terms and conditions</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= favicon_link_tag 'favicon.ico' %>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="<%= meta_description %>">
  <meta name="author" content="<%= meta_author %>">
  <meta name="Keywords" content="<%= meta_keywords %>">
 
  <title><%= full_title(yield(:title)) %></title>
 
 <!-- Font Awesome -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

<!-- Bootswatch CDN -->
<link href="//maxcdn.bootstrapcdn.com/bootswatch/3.3.2/lumen/bootstrap.min.css" rel="stylesheet">

<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>

<!-- Bootstrap -->
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    



 

  <%= csrf_meta_tags %>
  <!-- Alerts -->
      <% if notice %>
        <div class="alert alert-success" role="alert"><%= notice %></div>
      <% end %>
      <% if alert %>
        <div class="alert alert-danger" role="alert"><%= alert %></div>
      <% end %>


  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
  <![endif]-->
  <a href="#Top"></a>
</head>
<body>
 <div class="navbar navbar-fixed-top navbar-default" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to site_name, site_url, :class => "navbar-brand" %>
      </div>
      <div class="navbar-collapse collapse navbar-default-collapse">
         <ul class="nav navbar-nav pull-right">
          <li class="<%= 'active' if current_page?(events_path) %>"><%= link_to "Browse", events_path %></li>

          
          <li><% if current_user %>
                <%= link_to "My Account" , user_path(current_user)%>
                <% else %>
                <%= link_to "Sign in", login_path %>
                <% end %>
          </li>
          <li>
                <% if current_user %>
                <%= link_to "Sign out", logout_path %>
                <% end %>
          </li>
        </ul>
      </div><!-- /.nav-collapse -->
    </div><!-- /.container -->
  </div><!-- /.navbar -->
  <% if current_page?(root_path) %>
  <% if content_for?(:jumbotron) %>
    <div class="jumbotron">
      <div class="container">
        <%= yield :jumbotron %>
      </div>
    </div>
  <% end %>
<% else %>
  <div class="container">
<% end %>


<%= yield %>
<footer>
    <hr>
      <p class="pull-right">
        <%= link_to '<span class="glyphicon-class glyphicon glyphicon-chevron-up"></span> Back to top'.html_safe, '#Top' %>
      </p>
      <p>
        &copy; <%= Time.now.year %> <%= site_name %> 
        &bull;
        <%= link_to "Blog", "/blog" %></li>
        &bull;
        <%= link_to "Terms", "/terms" %></li>
      </p>
    </footer>
     </div> <!-- /container -->

<!-- AddThisEvent -->
  <script type="text/javascript" src="https://addthisevent.com/libs/1.5.8/ate.min.js"></script>

<!-- AddThisEvent Settings -->
<script type="text/javascript">
addthisevent.settings({
    license   : "aao8iuet5zp9iqw5sm9z",
    mouse     : false,
    css       : true,
    outlook   : {show:true, text:"Outlook Calendar"},
    google    : {show:true, text:"Google Calendar"},
    dropdown  : {order:"outlook,google"},
    callback  : ""
});
</script>

</body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      Please recheck the following <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/index.html.erb
<h1><a href="#">Please sign in</a></h1>

app/views/users/new.html.erb
<% provide(:title, 'Create') %>
<!DOCTYPE html>
<html>
<head>
    <title></title>
</head>

<body>
    <div class="container">
        <!-- Example row of columns -->

        <div class="row">
            <div class="col-md-6 col-md-offset-3">
            <h2 class="text-center">Create your account</h2>
        <p class="text-center">Already have an account? <%= link_to "Log in", login_path %></p><br>
                 <div class="well bs-component">   
                        

                       <%= simple_form_for(@user, html: { class: 'form-horizontal' }) do |form|%>
                        <%= render 'shared/error_messages', object: @user %>
                           
                                <div class="form-group">
                                <%= form.label :name, class: "col-lg-2 control-label", required: false %>

                                    <div class="col-lg-10">
                                        <%= form.input :name, input_html: {class: "form-control"}, label: false, placeholder: "Ernest Shackleton"%> 
                                    </div>
                                </div>

                                <div class="form-group">
                                    <%= form.label :email, class: "col-lg-2 control-label", required: false %>

                                    <div class="col-lg-10">
                                        <%= form.input :email, input_html: {class: "form-control"}, label: false, placeholder: "shackleton1850@kellogg.northwestern.edu" %>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <%= form.label :password, class: "col-lg-2 control-label", required: false %>

                                    <div class="col-lg-10">
                                        <%= form.input :password, input_html: {class: "form-control"}, label: false, required: false%>
                                    </div>
                                </div>
                               

                               <div class="form-group">
                               <%= form.label " ", class: "col-lg-2 control-label" %>
                                    <div class="col-lg-10">
                                        <%= form.input_field :terms_of_service, as: :boolean, label: false, required: false %> You have read and agree to the <%= link_to "Terms of Service", terms_path %>
                                    </div>
                                </div>
<div class="form-group">
                                <div class="col-lg-10 col-lg-offset-2">
<%= form.button :submit, class: "btn btn-success" %>  
                                </div>
                                    <% end %> </div>
                    
               </div>
            </div>
        </div>

        
    </div>
</body>
</html>

app/views/users/show.html.erb
<% provide(:title, 'Account') %>
<hr class="">
    <div class="container target">
        <div class="row">
            <div class="col-sm-8">
                <h1 class=""><%= @user.name %>
                </h1>
                <div class="btn-group"><%= link_to "Edit my details", edit_user_path(current_user), class: "btn  btn-default btn-xs"%>
                </div>
                <br>
                </div>
                <div class="col-sm-4"><%= image_tag @user.avatar.url(:thumb) %>
                </div>
            </div>
            <br>
                <div class="row">
                    <div class="col-sm-3">
                        <!--left col-->
                        <ul class="list-group">
                            <li class="list-group-item text-muted" contenteditable="false">Details</li>
                            <li class="list-group-item text-right">
                                <span class="pull-left">
                                    <strong>Date joined</strong>
                                </span><%= @user.created_at.strftime("%B %Y") %>
                            </li>
                            <li class="list-group-item text-right">
                                <span class="pull-left">
                                    <strong>Email</strong>
                                </span><%= @user.email %>
                            </li>
                            <li class="list-group-item text-right">
                                <span class="pull-left">
                                    <strong>Activities joined</strong>
                                </span><%= @reservations.count %>
                            </li>
                        </ul>
                        <div class="panel panel-default">
                            <div class="panel-heading">Social profiles</div>
                            <div class="panel-body">
                                <a href="<%= @user.facebook %>">
                                    <i class="fa fa-facebook fa-2x"></i>
                                </a>
                            </div>
                        </div>
                    </div>
                    <!--/col-3-->
                    <div class="col-sm-9" contenteditable="false" style="">
                        <div class="panel panel-default">
                            <div class="panel-heading"><%= @user.name %>'s description
                            </div>
                            <div class="panel-body"><%= @user.description %>
                            </div>
                        </div>
                    </div>
                </div>
        
    </div>    